
USE ola_project;

-- Count total rides by payment method

SELECT Payment_Method,
       COUNT(*) AS Total_Rides
FROM ola
GROUP BY Payment_Method;

-- Revenue generated by each vehicle type

SELECT Vehicle_Type,
       SUM(Booking_Value) AS Revenue
FROM ola
GROUP BY Vehicle_Type
ORDER BY Revenue DESC;

-- Top 10 pickup locations with highest ride demand

SELECT Pickup_Location,
       COUNT(*) AS Total_Rides
FROM ola
GROUP BY Pickup_Location
ORDER BY Total_Rides DESC
LIMIT 10;

-- Top 10 drop locations with highest ride demand

SELECT Drop_Location,
       COUNT(*) AS Total_Rides
FROM ola
GROUP BY Drop_Location
ORDER BY Total_Rides DESC
LIMIT 10;

-- Average driver rating for each vehicle type

SELECT Vehicle_Type,
       AVG(Driver_Ratings) AS Avg_Driver_Rating
FROM ola
GROUP BY Vehicle_Type;

-- Question 1:
-- Retrieve all successful bookings

SELECT *
FROM ola
WHERE Booking_Status = 'Success';


-- Question 2:
-- Find the average ride distance for each vehicle type

SELECT Vehicle_Type,
       AVG(Ride_Distance) AS Avg_Ride_Distance
FROM ola
GROUP BY Vehicle_Type;


-- Question 3:
-- Get the total number of rides cancelled by customers

SELECT COUNT(*) AS Total_Customer_Cancellations
FROM ola
WHERE Booking_Status = 'Cancelled by Customer';


-- Question 4:
-- List the top 5 customers who booked the highest number of rides

SELECT Customer_ID,
       COUNT(*) AS Total_Rides
FROM ola
GROUP BY Customer_ID
ORDER BY Total_Rides DESC
LIMIT 5;


-- Question 5:
-- Get the number of rides cancelled by drivers due to
-- Personal & Car related issue

SELECT COUNT(*) AS Driver_Cancelled_Rides
FROM ola
WHERE Canceled_Rides_by_Driver =
      'Personal & Car related issue';


-- Question 6:
-- Find the maximum and minimum driver ratings
-- for Prime Sedan bookings

SELECT MAX(Driver_Ratings) AS Maximum_Driver_Rating,
       MIN(Driver_Ratings) AS Minimum_Driver_Rating
FROM ola
WHERE Vehicle_Type = 'Prime Sedan';


-- Question 7:
-- Retrieve all rides where payment was made using UPI

SELECT *
FROM ola
WHERE Payment_Method = 'UPI';


-- Question 8:
-- Find the average customer rating per vehicle type

SELECT Vehicle_Type,
       AVG(Customer_Rating) AS Average_Customer_Rating
FROM ola
GROUP BY Vehicle_Type;


-- Question 9:
-- Calculate the total booking value of rides completed successfully

SELECT SUM(Booking_Value) AS Total_Revenue
FROM ola
WHERE Booking_Status = 'Success';


-- Question 10:
-- List all incomplete rides along with the reason

SELECT Booking_ID,
       Incomplete_Rides_Reason
FROM ola
WHERE Incomplete_Rides = 'Yes';